/* create table */

CREATE TABLE IF NOT EXISTS propagandas(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    cuit BIGINT,
    empresa VARCHAR(50) NOT NULL CHECK (empresa <> '')
);

CREATE TABLE IF NOT EXISTS temasmusicales(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR(50) NOT NULL CHECK (titulo <> ''),
    autor VARCHAR(50) NOT NULL CHECK (autor <> '')
);

CREATE TABLE IF NOT EXISTS directores(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dni INTEGER NOT NULL,
    nombre VARCHAR(50) NOT NULL CHECK (nombre <> ''),
    apellido VARCHAR(50) NOT NULL CHECK (apellido <> '')
);

CREATE TABLE IF NOT EXISTS locutores(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    dni INTEGER NOT NULL,
    nombre VARCHAR(50) NOT NULL CHECK (nombre <> ''),
    apellido VARCHAR(50) NOT NULL CHECK (apellido <> '')
);

CREATE TABLE IF NOT EXISTS programas(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    tituloprograma VARCHAR(50) NOT NULL CHECK (tituloprograma <> ''),
    dia DATE NOT NULL,
    horarioemision TIME NOT NULL,
    duracion TIME NOT NULL,
    fkdirectorid INTEGER REFERENCES directores(id),
    fklocutoresid INTEGER REFERENCES locutores(id)
);

CREATE TABLE IF NOT EXISTS periodos(
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    duracion TIME NOT NULL,
    fkprogramasid INTEGER REFERENCES programas(id),
    fkpropagandasid INTEGER REFERENCES propagandas(id),
    fktemasmusicalesid INTEGER REFERENCES temasmusicales(id)
);

/* ------------------------------------------------ */

-- Insert propagandas
INSERT INTO propagandas (cuit, empresa) VALUES (50111111113,'Ferreteria');
INSERT INTO propagandas (cuit, empresa) VALUES (50222222223,'Supermercado');
INSERT INTO propagandas (cuit, empresa) VALUES (50333333333,'Jugueteria');
INSERT INTO propagandas (cuit, empresa) VALUES (50444444443,'Gimnasio');
INSERT INTO propagandas (cuit, empresa) VALUES (50555555553,'Panaderia');
INSERT INTO propagandas (cuit, empresa) VALUES (50666666663,'Hotel');
INSERT INTO propagandas (cuit, empresa) VALUES (50777777773,'Remis');

select * from propagandas;

-- Insert temasmusicales
INSERT INTO temasmusicales (titulo, autor) values ('tema1', 'autor1');
INSERT INTO temasmusicales (titulo, autor) values ('tema2', 'autor2');
INSERT INTO temasmusicales (titulo, autor) values ('tema3', 'autor3');
INSERT INTO temasmusicales (titulo, autor) values ('tema4', 'autor4');
INSERT INTO temasmusicales (titulo, autor) values ('tema5', 'autor5');
INSERT INTO temasmusicales (titulo, autor) values ('tema6', 'autor6');
INSERT INTO temasmusicales (titulo, autor) values ('tema7', 'autor7');
INSERT INTO temasmusicales (titulo, autor) values ('tema8', 'autor8');
INSERT INTO temasmusicales (titulo, autor) values ('tema9', 'autor9');
INSERT INTO temasmusicales (titulo, autor) values ('tema10', 'autor10');

select * from temasmusicales;

-- Insert directores
INSERT INTO directores (dni, nombre, apellido) values (40111111, 'NombreDirector1', 'ApellidoDirector1');
INSERT INTO directores (dni, nombre, apellido) values (40222222, 'NombreDirector2', 'ApellidoDirector2');
INSERT INTO directores (dni, nombre, apellido) values (40333333, 'NombreDirector3', 'ApellidoDirector3');
INSERT INTO directores (dni, nombre, apellido) values (40444444, 'NombreDirector4', 'ApellidoDirector4');
INSERT INTO directores (dni, nombre, apellido) values (40555555, 'NombreDirector5', 'ApellidoDirector5');
INSERT INTO directores (dni, nombre, apellido) values (40666666, 'NombreDirector6', 'ApellidoDirector6');
INSERT INTO directores (dni, nombre, apellido) values (40777777, 'NombreDirector7', 'ApellidoDirector7');
INSERT INTO directores (dni, nombre, apellido) values (40888888, 'NombreDirector8', 'ApellidoDirector8');
INSERT INTO directores (dni, nombre, apellido) values (40999999, 'NombreDirector9', 'ApellidoDirector9');
INSERT INTO directores (dni, nombre, apellido) values (40000000, 'NombreDirector10', 'ApellidoDirectoro10');

select * from directores;

-- Insert locutores
INSERT INTO locutores (dni, nombre, apellido) values (30111111, 'NombreLocutor1', 'ApellidoLocutor1');
INSERT INTO locutores (dni, nombre, apellido) values (30222222, 'NombreLocutor2', 'ApellidoLocutor2');
INSERT INTO locutores (dni, nombre, apellido) values (30333333, 'NombreLocutor3', 'ApellidoLocutor3');
INSERT INTO locutores (dni, nombre, apellido) values (30444444, 'NombreLocutor4', 'ApellidoLocutor4');
INSERT INTO locutores (dni, nombre, apellido) values (30555555, 'NombreLocutor5', 'ApellidoLocutor5');
INSERT INTO locutores (dni, nombre, apellido) values (30666666, 'NombreLocutor6', 'ApellidoLocutor6');
INSERT INTO locutores (dni, nombre, apellido) values (30777777, 'NombreLocutor7', 'ApellidoLocutor7');
INSERT INTO locutores (dni, nombre, apellido) values (30888888, 'NombreLocutor8', 'ApellidoLocutor8');
INSERT INTO locutores (dni, nombre, apellido) values (30999999, 'NombreLocutor9', 'ApellidoLocutor9');
INSERT INTO locutores (dni, nombre, apellido) values (30000000, 'NombreLocutor10', 'ApellidoLocutor10');

select * from directores;

-- Insert programas
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa1', '2021/02/04', '01:00:00', '01:00:00', 1, 1)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa2', '2021/02/04', '02:00:00', '01:00:00', 2, 2)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa3', '2021/02/04', '03:00:00', '01:00:00', 3, 3)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa4', '2021/02/04', '04:00:00', '01:00:00', 4, 4)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa5', '2021/02/04', '05:00:00', '01:00:00', 5, 5)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa6', '2021/02/04', '06:00:00', '01:00:00', 6, 6)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa7', '2021/02/04', '07:00:00', '01:00:00', 7, 7)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa8', '2021/02/04', '08:00:00', '01:00:00', 8, 8)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa9', '2021/02/04', '09:00:00', '01:00:00', 9, 9)
INSERT INTO programas (tituloprograma, dia, horarioemision, duracion, fkdirectorid, fklocutoresid)
VALUES ('programa10', '2021/02/04', '10:00:00', '01:00:00', 10, 10)

select * from programas;

-- Insert Periodos

INSERT INTO periodos (duracion, fkprogramasid, fkpropagandasid, fktemasmusicalesid) values ('00:15:00', 1, 1, 1);
INSERT INTO periodos (duracion, fkprogramasid, fkpropagandasid, fktemasmusicalesid) values ('00:30:00', 2, 2, 2);
INSERT INTO periodos (duracion, fkprogramasid, fkpropagandasid, fktemasmusicalesid) values ('00:45:00', 3, 3, 3);
INSERT INTO periodos (duracion, fkprogramasid, fkpropagandasid, fktemasmusicalesid) values ('01:00:00', 4, 4, 4);